### ISSUE TITLE
Plan for 3.0.0

### ISSUE THREAD

**Issue by LinusU** [mafintosh/is-my-json-valid#169]
Things I want to get in:

- [ ] #162 - Throw on invalid schema format
- [ ] #161 - Handle custom formats with null values
- [ ] #53 - Minor tweaks regarding `required: true`
- [ ] Drop support for Node.js < 6

I would also be open to dropping support for any schema verison below 4.

Anything else that anyone would like to see fixed/improved/added? Please only bring up stuff that would actually be a breaking change. Fixing bugs should be done in patch releases.

**Comment by jimmywarting** [comment]
Since node 6 will be used:
- [ ] replace `xtend` with `Object.assign`
